[package]
name = "addition"
versionstarknet = "2.7.0"
sncast_std = { path = "../../../sncast_std" }
edition = "2023_10"

[dependencies]
starknet = "2.7.0"
sncast_std = { path = "../../../sncast_std" }

[dev-dependencies]
snforge_std = { path = "../../../snforge_std" }

[[target.starknet-contract]]
sierra = true

[lib]
