[package]
name = "fibonacci"
versionstarknet = "2.7.0"
sncast_std = { path = "../../../sncast_std" }
edition = "2023_10"

[scripts]
teststarknet = "2.7.0"
sncast_std = { path = "../../../sncast_std" }

[tool]
snforgestarknet = "2.7.0"
sncast_std = { path = "../../../sncast_std" }

[dependencies]
addition = { path = "../addition" }
starknet = "2.7.0"

[dev-dependencies]
snforge_stdstarknet = "2.7.0"
sncast_std = { path = "../../../sncast_std" }

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["addition::AdditionContract"]

[lib]
