[package]
name = "should_panic_test"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
