[package]
name = "docs"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
license-file.workspace = true

[dependencies]
regex = "1.11.1"
shell-words = "1.1.0"