[package]
name = "fuzz_testing"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet.workspace = true
assert_macros.workspace = true

[dev-dependencies]
snforge_std.workspace = true

[[target.lib]]
sierra = true

[scripts]
test = "snforge test"
