[workspace]
members = [
    "crates/*",
]

[workspace.scripts]
test = "snforge"

[workspace.tool.snforge]

[workspace.package]
version = "0.1.0"

[package]
name = "hello_workspaces"
versionstarknet = "2.7.0"
sncast_std = { path = "../../../sncast_std" }
edition = "2023_10"

[scripts]
teststarknet = "2.7.0"
sncast_std = { path = "../../../sncast_std" }

[tool]
snforgestarknet = "2.7.0"
sncast_std = { path = "../../../sncast_std" }

[dependencies]
fibonacci = { path = "crates/fibonacci" }
addition = { path = "crates/addition" }
starknet = "2.7.0"

[workspace.dependencies]
snforge_std = { path = "../../../snforge_std" }

[[target.starknet-contract]]
sierra = true
